version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - './.docker/mongodb:/data'
      - './.docker/mongodb/db:/data/db'
    ports:
      - '27017:27017'
    networks:
      - network
  
networks:
  network:
    driver: bridge